language: ruby
cache: bundler
bundler_args: "--without development"
rvm: 2.1.2
script:
  - bundle exec octopress build --trace

branches:
  only:
  - master

env:
  global:
    secure: "CXzSud7CdAxUmxfFosvonIBikf6AhlzyyCVIEBltucIr5eDsIIh7QkQfGZoY7TakTYjE1hdwZtrM2ALMX3ttXxnarpmnd96Rr2ZKXYeDlJBUKOf3H6o9u8a4+OyYcjDkGNisr5Sryuoz1F6l6i2GMZ6LurEsq2pIdjm0hdD0Ws4="
    secure: "Sqa3XdJo2Ohna8iOwmdVVYnim9++vNZVZ6LqFKn5jdGvfYqMVq68Cj6rWFs4+dMpcqpiFFGgsZBp+BcfREbq0ENwg3riDiSu0wLGSpIaOulDHeZO2Vh0dM+AdmcK6mjCJCt5PUuYfSyBqzsb0rjMYblwAiDMVfveEzNLNOwvVIw="

after_success:
  - puts ENV['AWS_ACCESS_KEY_ID']
  - puts ENV['AWS_SECRET_ACCESS_KEY']
  - bundle exec octopress deploy --trace
