language: ruby
cache: bundler
bundler_args: "--without development"
before_install:
- 'echo ''gem: --no-ri --no-rdoc'' > ~/.gemrc'
env:
  global:
  - secure: KH+R52si3dGuz5yODWziwE2Jvt082KuqWnM7Cah8+VrBBm8qWdNBeJTcXnws7aGvYrUYXmFogSG2PYerLJkbABykokUCNqM1oRX7/mKvOkKmB/zRGK5oX7unfH3vPleKodE1dMZSRwWIrV6Xmo5/qtchmosd+CYkP8irTQKEKvE=
  - secure: PH8Fyt6FhqQH7IAN1xXiGTLamK3CuxFOXjn6o0tN+Q7R4p2xrmpxLDkudivt/zdmBKRLL/LkkFedr0QmI6U4P7rVvMDxzVafGQb2/9nFciOwfuUnqh42fVeO+5ckl516KIOg9ycFGfC5k4eG2Vd7fMrmXK58FG/yWVQRTMd6O5A=
before_script:
- ruby .travis_yaml_config.rb
script:
- bundle exec jekyll build --trace
branches:
  only:
  - master
after_success:
- bundle exec s3_website push
