# Site settings
title: John Write Code
email: hello@johnkellyferguson.com
description: ''
baseurl: ''
url: 'http://johnwritecode.com'
twitter_username: johnkferguson
github_username:  johnkellyferguson

markdown: kramdown
permalink: /:title/
exclude: ['Gemfile', 'Gemfile.lock', 'Guardfile', 'README.md', 'vendor/**']

gems:
  - jekyll-sitemap

assets:
  dirname: assets
  baseurl: /assets/
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
  js_compressor: uglifier
  css_compressor: sass
  cachebust: hard
  cache: false
  gzip: [ text/css, application/javascript ]
