---
title: John Kelly Ferguson
email: hello@johnkellyferguson.com
description: ''
baseurl: ''
url: http://johnwritecode.com
twitter_username: johnkferguson
github_username: johnkellyferguson
markdown: redcarpet
redcarpet:
  extensions:
  - tables
  - no_intra_emphasis
  - autolink
  - smart
permalink: "/:title/"
exclude:
- Gemfile
- Gemfile.lock
- Guardfile
- README.md
- vendor/**
plugins:
- jekyll-sitemap
assets:
  dirname: assets
  baseurl: "/assets/"
  sources:
  - _assets/javascripts
  - _assets/stylesheets
  - _assets/images
  cachebust: hard
  cache: false
  gzip: false
